
/* autogenerated from rem.orc */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#ifndef DISABLE_ORC
#include <orc/orc.h>
#endif

#ifndef _ORC_INTEGER_TYPEDEFS_
#define _ORC_INTEGER_TYPEDEFS_
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#include <stdint.h>
typedef int8_t orc_int8;
typedef int16_t orc_int16;
typedef int32_t orc_int32;
typedef int64_t orc_int64;
typedef uint8_t orc_uint8;
typedef uint16_t orc_uint16;
typedef uint32_t orc_uint32;
typedef uint64_t orc_uint64;
#define ORC_UINT64_C(x) UINT64_C(x)
#elif defined(_MSC_VER)
typedef signed __int8 orc_int8;
typedef signed __int16 orc_int16;
typedef signed __int32 orc_int32;
typedef signed __int64 orc_int64;
typedef unsigned __int8 orc_uint8;
typedef unsigned __int16 orc_uint16;
typedef unsigned __int32 orc_uint32;
typedef unsigned __int64 orc_uint64;
#define ORC_UINT64_C(x) (x##Ui64)
#else
#include <limits.h>
typedef signed char orc_int8;
typedef short orc_int16;
typedef int orc_int32;
typedef unsigned char orc_uint8;
typedef unsigned short orc_uint16;
typedef unsigned int orc_uint32;
#if INT_MAX == LONG_MAX
typedef long long orc_int64;
typedef unsigned long long orc_uint64;
#define ORC_UINT64_C(x) (x##ULL)
#else
typedef long orc_int64;
typedef unsigned long orc_uint64;
#define ORC_UINT64_C(x) (x##UL)
#endif
#endif
typedef union { orc_int16 i; orc_int8 x2[2]; } orc_union16;
typedef union { orc_int32 i; float f; orc_int16 x2[2]; orc_int8 x4[4]; } orc_union32;
typedef union { orc_int64 i; double f; orc_int32 x2[2]; float x2f[2]; orc_int16 x4[4]; } orc_union64;
#endif

void convert_yuyv_to_yuv420p (orc_uint16 * d1, int d1_stride, orc_uint16 * d2, int d2_stride, orc_uint8 * d3, int d3_stride, orc_uint8 * d4, int d4_stride, const orc_uint32 * s1, int s1_stride, const orc_uint32 * s2, int s2_stride, int n, int m);

void vidconv_init (void);


/* begin Orc C target preamble */
#define ORC_CLAMP(x,a,b) ((x)<(a) ? (a) : ((x)>(b) ? (b) : (x)))
#define ORC_ABS(a) ((a)<0 ? -(a) : (a))
#define ORC_MIN(a,b) ((a)<(b) ? (a) : (b))
#define ORC_MAX(a,b) ((a)>(b) ? (a) : (b))
#define ORC_SB_MAX 127
#define ORC_SB_MIN (-1-ORC_SB_MAX)
#define ORC_UB_MAX 255
#define ORC_UB_MIN 0
#define ORC_SW_MAX 32767
#define ORC_SW_MIN (-1-ORC_SW_MAX)
#define ORC_UW_MAX 65535
#define ORC_UW_MIN 0
#define ORC_SL_MAX 2147483647
#define ORC_SL_MIN (-1-ORC_SL_MAX)
#define ORC_UL_MAX 4294967295U
#define ORC_UL_MIN 0
#define ORC_CLAMP_SB(x) ORC_CLAMP(x,ORC_SB_MIN,ORC_SB_MAX)
#define ORC_CLAMP_UB(x) ORC_CLAMP(x,ORC_UB_MIN,ORC_UB_MAX)
#define ORC_CLAMP_SW(x) ORC_CLAMP(x,ORC_SW_MIN,ORC_SW_MAX)
#define ORC_CLAMP_UW(x) ORC_CLAMP(x,ORC_UW_MIN,ORC_UW_MAX)
#define ORC_CLAMP_SL(x) ORC_CLAMP(x,ORC_SL_MIN,ORC_SL_MAX)
#define ORC_CLAMP_UL(x) ORC_CLAMP(x,ORC_UL_MIN,ORC_UL_MAX)
#define ORC_SWAP_W(x) ((((x)&0xff)<<8) | (((x)&0xff00)>>8))
#define ORC_SWAP_L(x) ((((x)&0xff)<<24) | (((x)&0xff00)<<8) | (((x)&0xff0000)>>8) | (((x)&0xff000000)>>24))
#define ORC_SWAP_Q(x) ((((x)&ORC_UINT64_C(0xff))<<56) | (((x)&ORC_UINT64_C(0xff00))<<40) | (((x)&ORC_UINT64_C(0xff0000))<<24) | (((x)&ORC_UINT64_C(0xff000000))<<8) | (((x)&ORC_UINT64_C(0xff00000000))>>8) | (((x)&ORC_UINT64_C(0xff0000000000))>>24) | (((x)&ORC_UINT64_C(0xff000000000000))>>40) | (((x)&ORC_UINT64_C(0xff00000000000000))>>56))
#define ORC_PTR_OFFSET(ptr,offset) ((void *)(((unsigned char *)(ptr)) + (offset)))
#define ORC_DENORMAL(x) ((x) & ((((x)&0x7f800000) == 0) ? 0xff800000 : 0xffffffff))
#define ORC_ISNAN(x) ((((x)&0x7f800000) == 0x7f800000) && (((x)&0x007fffff) != 0))
#define ORC_DENORMAL_DOUBLE(x) ((x) & ((((x)&ORC_UINT64_C(0x7ff0000000000000)) == 0) ? ORC_UINT64_C(0xfff0000000000000) : ORC_UINT64_C(0xffffffffffffffff)))
#define ORC_ISNAN_DOUBLE(x) ((((x)&ORC_UINT64_C(0x7ff0000000000000)) == ORC_UINT64_C(0x7ff0000000000000)) && (((x)&ORC_UINT64_C(0x000fffffffffffff)) != 0))
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define ORC_RESTRICT restrict
#elif defined(__GNUC__) && __GNUC__ >= 4
#define ORC_RESTRICT __restrict__
#else
#define ORC_RESTRICT
#endif
/* end Orc C target preamble */



/* convert_yuyv_to_yuv420p */
#ifdef DISABLE_ORC
void
convert_yuyv_to_yuv420p (orc_uint16 * d1, int d1_stride, orc_uint16 * d2, int d2_stride, orc_uint8 * d3, int d3_stride, orc_uint8 * d4, int d4_stride, const orc_uint32 * s1, int s1_stride, const orc_uint32 * s2, int s2_stride, int n, int m){
  int i;
  int j;
  orc_union16 * ORC_RESTRICT ptr0;
  orc_union16 * ORC_RESTRICT ptr1;
  orc_int8 * ORC_RESTRICT ptr2;
  orc_int8 * ORC_RESTRICT ptr3;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var40;
  orc_union32 var41;
  orc_int8 var42;
  orc_int8 var43;
  orc_union16 var44;
  orc_union16 var45;
  orc_union32 var46;
  orc_union32 var47;
  orc_union16 var48;
  orc_union16 var49;
  orc_int8 var50;
  orc_int8 var51;
  orc_union16 var52;
  orc_union16 var53;
  orc_int8 var54;
  orc_int8 var55;

  for (j = 0; j < m; j++) {
    ptr0 = ORC_PTR_OFFSET(d1, d1_stride * j);
    ptr1 = ORC_PTR_OFFSET(d2, d2_stride * j);
    ptr2 = ORC_PTR_OFFSET(d3, d3_stride * j);
    ptr3 = ORC_PTR_OFFSET(d4, d4_stride * j);
    ptr4 = ORC_PTR_OFFSET(s1, s1_stride * j);
    ptr5 = ORC_PTR_OFFSET(s2, s2_stride * j);


    for (i = 0; i < n; i++) {
      /* 0: loadl */
      var40 = ptr4[i];
      /* 1: swapl */
      var46.i = ORC_SWAP_L(var40.i);
      /* 2: loadl */
      var41 = ptr5[i];
      /* 3: swapl */
      var47.i = ORC_SWAP_L(var41.i);
      /* 4: splitlw */
      var48.i = (var46.i >> 16) & 0xffff;
    var49.i = var46.i & 0xffff;
      /* 5: select1wb */
      var50 = ((orc_uint16)var48.i >> 8)&0xff;
      /* 6: select0wb */
      var42 = (orc_uint16)var48.i & 0xff;
      /* 7: storeb */
      ptr2[i] = var42;
      /* 8: select1wb */
      var51 = ((orc_uint16)var49.i >> 8)&0xff;
      /* 9: select0wb */
      var43 = (orc_uint16)var49.i & 0xff;
      /* 10: storeb */
      ptr3[i] = var43;
      /* 11: mergebw */
      var44.i = ((orc_uint8)var50 & 0x00ff) | ((orc_uint8)var51 << 8);
      /* 12: storew */
      ptr0[i] = var44;
      /* 13: splitlw */
      var52.i = (var47.i >> 16) & 0xffff;
    var53.i = var47.i & 0xffff;
      /* 14: select1wb */
      var54 = ((orc_uint16)var52.i >> 8)&0xff;
      /* 15: select1wb */
      var55 = ((orc_uint16)var53.i >> 8)&0xff;
      /* 16: mergebw */
      var45.i = ((orc_uint8)var54 & 0x00ff) | ((orc_uint8)var55 << 8);
      /* 17: storew */
      ptr1[i] = var45;
    }
  }

}

#else
static void
_backup_convert_yuyv_to_yuv420p (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int j;
  int n = ex->n;
  int m = ex->params[ORC_VAR_A1];
  orc_union16 * ORC_RESTRICT ptr0;
  orc_union16 * ORC_RESTRICT ptr1;
  orc_int8 * ORC_RESTRICT ptr2;
  orc_int8 * ORC_RESTRICT ptr3;
  const orc_union32 * ORC_RESTRICT ptr4;
  const orc_union32 * ORC_RESTRICT ptr5;
  orc_union32 var40;
  orc_union32 var41;
  orc_int8 var42;
  orc_int8 var43;
  orc_union16 var44;
  orc_union16 var45;
  orc_union32 var46;
  orc_union32 var47;
  orc_union16 var48;
  orc_union16 var49;
  orc_int8 var50;
  orc_int8 var51;
  orc_union16 var52;
  orc_union16 var53;
  orc_int8 var54;
  orc_int8 var55;

  printf("BACKUP called\n");

  for (j = 0; j < m; j++) {
    ptr0 = ORC_PTR_OFFSET(ex->arrays[0], ex->params[0] * j);
    ptr1 = ORC_PTR_OFFSET(ex->arrays[1], ex->params[1] * j);
    ptr2 = ORC_PTR_OFFSET(ex->arrays[2], ex->params[2] * j);
    ptr3 = ORC_PTR_OFFSET(ex->arrays[3], ex->params[3] * j);
    ptr4 = ORC_PTR_OFFSET(ex->arrays[4], ex->params[4] * j);
    ptr5 = ORC_PTR_OFFSET(ex->arrays[5], ex->params[5] * j);


    for (i = 0; i < n; i++) {
      /* 0: loadl */
      var40 = ptr4[i];
      /* 1: swapl */
      var46.i = ORC_SWAP_L(var40.i);
      /* 2: loadl */
      var41 = ptr5[i];
      /* 3: swapl */
      var47.i = ORC_SWAP_L(var41.i);
      /* 4: splitlw */
      var48.i = (var46.i >> 16) & 0xffff;
    var49.i = var46.i & 0xffff;
      /* 5: select1wb */
      var50 = ((orc_uint16)var48.i >> 8)&0xff;
      /* 6: select0wb */
      var42 = (orc_uint16)var48.i & 0xff;
      /* 7: storeb */
      ptr2[i] = var42;
      /* 8: select1wb */
      var51 = ((orc_uint16)var49.i >> 8)&0xff;
      /* 9: select0wb */
      var43 = (orc_uint16)var49.i & 0xff;
      /* 10: storeb */
      ptr3[i] = var43;
      /* 11: mergebw */
      var44.i = ((orc_uint8)var50 & 0x00ff) | ((orc_uint8)var51 << 8);
      /* 12: storew */
      ptr0[i] = var44;
      /* 13: splitlw */
      var52.i = (var47.i >> 16) & 0xffff;
    var53.i = var47.i & 0xffff;
      /* 14: select1wb */
      var54 = ((orc_uint16)var52.i >> 8)&0xff;
      /* 15: select1wb */
      var55 = ((orc_uint16)var53.i >> 8)&0xff;
      /* 16: mergebw */
      var45.i = ((orc_uint8)var54 & 0x00ff) | ((orc_uint8)var55 << 8);
      /* 17: storew */
      ptr1[i] = var45;
    }
  }

}

static OrcProgram *_orc_program_convert_yuyv_to_yuv420p;
void
convert_yuyv_to_yuv420p (orc_uint16 * d1, int d1_stride, orc_uint16 * d2, int d2_stride, orc_uint8 * d3, int d3_stride, orc_uint8 * d4, int d4_stride, const orc_uint32 * s1, int s1_stride, const orc_uint32 * s2, int s2_stride, int n, int m)
{
  OrcExecutor _ex, *ex = &_ex;
  OrcProgram *p = _orc_program_convert_yuyv_to_yuv420p;
  void (*func) (OrcExecutor *);

  ex->program = p;

  ex->n = n;
  ORC_EXECUTOR_M(ex) = m;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_D1] = d1_stride;
  ex->arrays[ORC_VAR_D2] = d2;
  ex->params[ORC_VAR_D2] = d2_stride;
  ex->arrays[ORC_VAR_D3] = d3;
  ex->params[ORC_VAR_D3] = d3_stride;
  ex->arrays[ORC_VAR_D4] = d4;
  ex->params[ORC_VAR_D4] = d4_stride;
  ex->arrays[ORC_VAR_S1] = (void *)s1;
  ex->params[ORC_VAR_S1] = s1_stride;
  ex->arrays[ORC_VAR_S2] = (void *)s2;
  ex->params[ORC_VAR_S2] = s2_stride;

  func = p->code_exec;
  func (ex);
}
#endif


void
vidconv_init (void)
{
#ifndef DISABLE_ORC
  {
    /* convert_yuyv_to_yuv420p */
    OrcProgram *p;
    OrcCompileResult result;
    OrcTarget *target_sse;

      p = orc_program_new ();
      orc_program_set_2d (p);
      orc_program_set_name (p, "convert_yuyv_to_yuv420p");
      orc_program_set_backup_function (p, _backup_convert_yuyv_to_yuv420p);
      orc_program_add_destination (p, 2, "d1");
      orc_program_add_destination (p, 2, "d2");
      orc_program_add_destination (p, 1, "d3");
      orc_program_add_destination (p, 1, "d4");
      orc_program_add_source (p, 4, "s1");
      orc_program_add_source (p, 4, "s2");
      orc_program_add_temporary (p, 4, "t1");
      orc_program_add_temporary (p, 4, "t2");
      orc_program_add_temporary (p, 2, "t3");
      orc_program_add_temporary (p, 2, "t4");
      orc_program_add_temporary (p, 1, "t5");
      orc_program_add_temporary (p, 1, "t6");
      orc_program_add_temporary (p, 2, "t7");
      orc_program_add_temporary (p, 2, "t8");

      orc_program_append_2 (p, "swapl", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "swapl", 0, ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "splitlw", 0, ORC_VAR_T3, ORC_VAR_T4, ORC_VAR_T1, ORC_VAR_D1);
      orc_program_append_2 (p, "select1wb", 0, ORC_VAR_T5, ORC_VAR_T3, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "select0wb", 0, ORC_VAR_D3, ORC_VAR_T3, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "select1wb", 0, ORC_VAR_T6, ORC_VAR_T4, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "select0wb", 0, ORC_VAR_D4, ORC_VAR_T4, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "mergebw", 0, ORC_VAR_D1, ORC_VAR_T5, ORC_VAR_T6, ORC_VAR_D1);
      orc_program_append_2 (p, "splitlw", 0, ORC_VAR_T3, ORC_VAR_T4, ORC_VAR_T2, ORC_VAR_D1);
      orc_program_append_2 (p, "select1wb", 0, ORC_VAR_T5, ORC_VAR_T3, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "select1wb", 0, ORC_VAR_T6, ORC_VAR_T4, ORC_VAR_D1, ORC_VAR_D1);
      orc_program_append_2 (p, "mergebw", 0, ORC_VAR_D2, ORC_VAR_T5, ORC_VAR_T6, ORC_VAR_D1);

      target_sse = orc_target_get_by_name ("sse");

      result = orc_program_compile (p);

      printf("target sse: res=%d\n", result);

    _orc_program_convert_yuyv_to_yuv420p = p;
  }
#endif
}


